spring:
  r2dbc:
    url: r2dbc:postgresql://${MINIKUBE_IP}:32017
    username: postgres
    password: 1234
  data:
    mongodb:
      uri: mongodb://${MINIKUBE_IP}:32018/plog_files
    redis:
      host: ${MINIKUBE_IP}
      port: 6379
  datasource:
    url: jdbc:${MINIKUBE_IP}://localhost:32017
    username: postgres
    password: 1234
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
#  cloud:
#    vault:
#      token:
#      uri: