spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432
    username: postgres
    password: 1234
  data:
    mongodb:
      uri: mongodb://localhost:27017/plog_files
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432
    username: postgres
    password: 1234
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
#  cloud:
#    vault:
#      token:
#      uri: