spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432
    username: postgres
    password: 1234
  data:
    mongodb:
      uri: mongodb://localhost:27017
    redis:
      host: localhost
      port: 6379
  cloud:
    vault:
      token:
      uri:
      
    .

